name: lint

on:
  push:
    paths:
      - '.github/workflows/**.yml'
      - '**.lua'
      - '.luarc.json'
  pull_request:
    paths:
      - '**.lua'
      - '.luarc.json'

jobs:
  lint:
    runs-on: ubuntu-latest

    env:
      LLS_VERSION: 3.18.2

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cache lua-language-server
      uses: actions/cache@v4
      id: llscache
      with:
        path: ~/.lua-language-server
        key: ${{ runner.os }}-lua-language-server-${{ env.LLS_VERSION }}

    - name: Install lua-language-server
      if: steps.llscache.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/.lua-language-server
        wget -qO- "https://github.com/LuaLS/lua-language-server/releases/download/${LLS_VERSION}/lua-language-server-${LLS_VERSION}-linux-x64.tar.gz" | tar -xzf - -C ~/.lua-language-server

    - name: Check
      run: ~/.lua-language-server/bin/lua-language-server --check "$GITHUB_WORKSPACE" --checklevel=Warning
